### ISSUE TITLE
Time format error for some records

### ISSUE THREAD

**Issue by SettPaing7** [naung9/general-isgm-cheattools#1]
For some records time format doesn't match error occur.
`xmlrpc.client.Fault: <Fault 1: 'Traceback (most recent call last):\n  File "/opt/odoo/odoo10/odoo/service/wsgi_server.py", line 56, in xmlrpc_return\n    result = odoo.http.dispatch_rpc(service, method, params)\n  File "/opt/odoo/odoo10/odoo/http.py", line 118, in dispatch_rpc\n    result = dispatch(method, params)\n  File "/opt/odoo/odoo10/odoo/service/model.py", line 38, in dispatch\n    res = fn(db, uid, *params)\n  File "/opt/odoo/odoo10/odoo/service/model.py", line 175, in execute_kw\n    return execute(db, uid, obj, method, *args, **kw or {})\n  File "/opt/odoo/odoo10/odoo/service/model.py", line 101, in wrapper\n    return f(dbname, *args, **kwargs)\n  File "/opt/odoo/odoo10/odoo/service/model.py", line 182, in execute\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\n  File "/opt/odoo/odoo10/odoo/service/model.py", line 171, in execute_cr\n    return odoo.api.call_kw(recs, method, args, kw)\n  File "/opt/odoo/odoo10/odoo/api.py", line 689, in call_kw\n    return call_kw_multi(method, model, args, kwargs)\n  File "/opt/odoo/odoo10/odoo/api.py", line 680, in call_kw_multi\n    result = method(recs, *args, **kwargs)\n  File "/opt/odoo/odoo10-custom-addons/isgm_project_ext_v10/models/manual_attencance.py", line 2441, in write\n    manual_sign_in = datetime.datetime.strptime(str(manual_sign_in), \'%Y-%m-%d %H:%M:%S\')\n  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime\n    (data_string, format))\nValueError: time data \'False\' does not match format \'%Y-%m-%d %H:%M:%S\'\n'>`

**Comment by SettPaing7** [comment]
Issue occur when only check in or check out time is present.

**Comment by SettPaing7** [comment]
Issue occurred from server side.
